# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
 name: KDIOTPool
 demands: docker

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Entek_Assistant_Docker_Registry'
    repository: 'entekrepository'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: '$(Build.SourceVersion)'
    addPipelineData: false
    addBaseImageData: false

- task: Docker@2
  inputs:
    containerRegistry: 'Entek_Assistant_Docker_Registry'
    repository: 'entekrepository'
    command: 'push'
    tags: '$(Build.SourceVersion)'
    addPipelineData: false
    addBaseImageData: false