version: '3.8'

services:
  fastapi_app:
    build: .
    image: ayrimci_dil_app
    ports:
      - "5001:5000"
    volumes:
      - ./:/app/
      - ./logs:/app/logs
    env_file:
      - .env
    command: "/opt/venv/bin/uvicorn app:app --reload --host 0.0.0.0 --port 5001 --ssl-keyfile './ssl/kockariyerimkey_2024.pem' --ssl-certfile './ssl/kockariyerimcert_2024.pem' --ssl-keyfile-password 'Aa123456.'"