azure-ai-search:
  endpoint: https://ai-search-rag-product-dev.search.windows.net
  index-name: ai-search-rag-product-dev
llm:
  endpoint: https://openai-sales-assistant-dev.openai.azure.com/
  api-version: 2024-04-01-preview
  deployment: LLM
  embedding: Text-Embedding
  temperature: 0.0
  seed: 1905