version: '3.8'

services:
  evaluation-fastapi:
    build: .
    image: evaluation-fastapi
    ports:
      - 3000:3000
    volumes:
      - ./:/app/
    command: "/opt/venv/bin/uvicorn app:app --reload --host 0.0.0.0 --port 3000"