name: CorporateAI-Sales-Assistant
description: CorporateAI-Sales-Assistant
runtime:
  name: python
  options:
    toolchain: pip
    virtualenv: venv
config:
  pulumi:tags:
    value:
      pulumi:template: azure-python
